### ISSUE TITLE
Sneak for long range?

### ISSUE THREAD

**Issue by DukeVindzor** [TheDreamSanctuary/Multitool#8]
So personally, not a huge fan of this feature from previous plugins because a lot of us use creative flight where sneaking cause you to descend. I would rather have some other minecraft function activate this feature or simply do like VoxelSniper and only have a command toggle it. Any thoughts?

**Comment by AceDexter** [comment]
@DukeVindzor I too use 'sneak' to descend while in flight which is quite possibly why I was never aware that there was a long-range function while applying sneak. I would submit that a command would be best to toggle this feature on and off.

**Comment by DukeVindzor** [comment]
Conclusion: No sneak feature, long range only by command!
